In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [41]:
file = pd.read_csv('Airbnb_Open_Data.csv')
df = pd.DataFrame(file)

C:\Users\Public\Documents\Wondershare\CreatorTemp\ipykernel_3648\1492880517.py:1: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  file = pd.read_csv('Airbnb_Open_Data.csv')

In [3]:
df.shape

(102599, 26)

In [4]:
df.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

In [42]:
df.drop(columns=['license'], inplace=True)

In [10]:
df.head()

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$966,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$142,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$620,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and..."
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$368,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$204,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th..."

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 25 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  object
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
dtypes: float64(9), int64(2), object(14)
memory usage: 19.6+ MB

In [13]:
df['neighbourhood group'].nunique()

7

In [18]:
neighbour_group = df.groupby('neighbourhood group')['NAME'].count()

In [19]:
print (neighbour_group)

neighbourhood group
Bronx             2704
Brooklyn         41734
Manhattan        43689
Queens           13239
Staten Island      954
brookln              1
manhatan             1
Name: NAME, dtype: int64

In [43]:
df.drop(columns = 'id', inplace = True)

In [61]:
for i in df.columns:
    abc = df.groupby(i)['NAME'].count()
    print (i) 
    print (abc)

NAME
NAME
 Private 1 bdrm Lefferts Gr, BK apt                   2
! ! ! Coliving: live, work, create                    4
!! CLASSIC, LUXURY & CHARM !! By Central Park UWS     2
!!! Beautiful private room with backyard.             4
!!! Outpost Coliving . Shared twin room               4
                                                     ..
🥰Lovely 1 bedroom/5 minutes walk to timessquare       1
🧑🏼‍✈️Private Room LGA ✈️                              1
🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST      1
🪴XL dojo 🌾 shared green yogi palace apt 🌿             1
🪴🛋🌞 Unique sunny clean brownstone studio 1st floor    1
Name: NAME, Length: 61281, dtype: int64
host_identity_verified
host_identity_verified
unconfirmed    51083
verified       50989
Name: NAME, dtype: int64
host name
host name
#NAME?                      2
'Cil                        1
(Ari) HENRY LEE             2
(Email hidden by Airbnb)    8
(Mary) Haiy                 4
                           ..
단비                          1
빈나                          2
소정                          3
진                           1
현선                          2
Name: NAME, Length: 13190, dtype: int64
neighbourhood group
neighbourhood group
Bronx             2704
Brooklyn         41734
Manhattan        43689
Queens           13239
Staten Island      954
brookln              1
manhatan             1
Name: NAME, dtype: int64
neighbourhood
neighbourhood
Allerton             97
Arden Heights         9
Arrochar             52
Arverne             223
Astoria            1873
                   ...
Windsor Terrace     331
Woodhaven           191
Woodlawn             29
Woodrow               3
Woodside            587
Name: NAME, Length: 224, dtype: int64
instant_bookable
instant_bookable
False    51354
True     50898
Name: NAME, dtype: int64
cancellation_policy
cancellation_policy
flexible    34000
moderate    34262
strict      34016
Name: NAME, dtype: int64
room type
room type
Entire home/apt    53575
Hotel room           116
Private room       46438
Shared room         2220
Name: NAME, dtype: int64
Construction year
Construction year
2003.0    5105
2004.0    5020
2005.0    5120
2006.0    5213
2007.0    5095
2008.0    5211
2009.0    5152
2010.0    5152
2011.0    5043
2012.0    5118
2013.0    5013
2014.0    5227
2015.0    5083
2016.0    5001
2017.0    5053
2018.0    5045
2019.0    5192
2020.0    5143
2021.0    5034
2022.0    5124
Name: NAME, dtype: int64
price
price
$1,000     105
$1,001      96
$1,002      87
$1,003     105
$1,004     100
          ...
$995       111
$996        66
$997        97
$998        93
$999        69
Name: NAME, Length: 1151, dtype: int64
service fee
service fee
0      273
10     266
11     424
12     433
13     430
      ...
236    423
237    465
238    458
239    399
240    248
Name: NAME, Length: 232, dtype: int64
minimum nights
minimum nights
-1223    1
-365     1
-200     1
-125     1
-12      1
        ..
 1000    0
 1250    1
 2645    1
 3455    1
 5645    1
Name: NAME, Length: 154, dtype: int64
number of reviews
number of reviews
0.0       15698
1.0       10384
2.0        7161
3.0        5369
4.0        4141
          ...
849.0         1
884.0         1
966.0         1
1010.0        1
1024.0        1
Name: NAME, Length: 476, dtype: int64
last review
last review
1/1/2013      3
1/1/2015      8
1/1/2016     41
1/1/2017    212
1/1/2018    286
           ...
9/9/2016      7
9/9/2017     18
9/9/2018     56
9/9/2020      2
9/9/2021      7
Name: NAME, Length: 2477, dtype: int64
reviews per month
reviews per month
0.01       66
0.02     1159
0.03     1665
0.04     1268
0.05     1486
         ...
57.31       1
58.50       2
65.74       1
84.49       1
90.00       1
Name: NAME, Length: 1016, dtype: int64
review rate number
review rate number
1.0     9183
2.0    23052
3.0    23209
4.0    23268
5.0    23319
Name: NAME, dtype: int64
calculated host listings count
calculated host listings count
1.0      63279
2.0      14404
3.0       6559
4.0       3539
5.0       1985
         ...
208.0      204
218.0       29
232.0      271
327.0      468
332.0       41
Name: NAME, Length: 78, dtype: int64
availability 365
availability 365
-10.0      37
-9.0       46
-8.0       50
-7.0       36
-6.0       31
           ..
 423.0     48
 424.0     38
 425.0     50
 426.0     46
 3677.0     1
Name: NAME, Length: 438, dtype: int64

In [22]:
df.columns

Index(['NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules'],
      dtype='object')

In [46]:
df.rename(columns = {'NAME': 'Name'})

,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,...,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,...,$966,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,...,$142,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,...,$620,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and..."
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,...,$368,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,...,$204,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,...,$844,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...
102595,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,...,$837,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...
102596,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,...,$988,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN
102597,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,...,$546,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN
102598,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,...,"$1,032",$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN

In [48]:
useless_col = ['lat', 'long', 'country', 'country code']
df.drop (columns = useless_col, inplace = True)

In [7]:
df.columns

Index(['NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'instant_bookable',
       'cancellation_policy', 'room type', 'Construction year', 'price',
       'service fee', 'minimum nights', 'number of reviews', 'last review',
       'reviews per month', 'review rate number',
       'calculated host listings count', 'availability 365', 'house_rules'],
      dtype='object')

In [8]:
df['house_rules'].unique()

array(["Clean up and treat the home the way you'd like your home to be treated.  No smoking.",
       'Pet friendly but please confirm with me if the pet you are planning on bringing with you is OK. I have a cute and quiet mixed chihuahua. I could accept more guests (for an extra fee) but this also needs to be confirmed beforehand. Also friends traveling together could sleep in separate beds for an extra fee (the second bed is either a sofa bed or inflatable bed). Smoking is only allowed on the porch.',
       "I encourage you to use my kitchen, cooking and laundry facilities. There is no additional charge to use the washer/dryer in the basement.  No smoking, inside or outside. Come home as late as you want.  If you come home stumbling drunk, it's OK the first time. If you do it again, and you wake up me or the neighbors downstairs, we will be annoyed.  (Just so you know . . . )",
       ...,
       '15 nights minimum stay No pets at any time No smoking Please be mindful of the furniture and personal belongings, it was all furnished with designer pieces and hard to replace things.',
       'House rules: Guests agree to the following terms and conditions 1.Guest(s) agree to NO PARTIES anywhere on the property. Legal action will be taken for parties that cause damages to the unit, property, reputation, or relationship with building staff or other residents.  2.Smoking of any kind is not permitted in the unit or on the premises.  3.Guests agree to abide by maximum occupancy of unit, and observe quiet hours between 9pm and 9am 4.Guests are responsible for action of ALL GUESTS occupying their unit at all times.  5.Guests agree to return all keys, remotes, and parking passes. Replacement fees may apply for unreturned items 6.Guests understand that onsite building staff (maintenance and concierge) are not affiliated with Jordan or AIRBNB. Please contact me directly for any needed items. 7.Guests understand that no pets are to be in the unit.  8.Guests agree to pay replacement cost for any unreturned items, and $125 per hour fee for unauthorized early checkin or late checkout.  22',
       '16 nights minimum stay, no smoking or pets.'], dtype=object)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 20 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   NAME                            102349 non-null  object
 1   host id                         102599 non-null  int64
 2   host_identity_verified          102310 non-null  object
 3   host name                       102193 non-null  object
 4   neighbourhood group             102570 non-null  object
 5   neighbourhood                   102583 non-null  object
 6   instant_bookable                102494 non-null  object
 7   cancellation_policy             102523 non-null  object
 8   room type                       102599 non-null  object
 9   Construction year               102385 non-null  float64
 10  price                           102352 non-null  object
 11  service fee                     102326 non-null  object
 12  minimum nights                  102190 non-null  float64
 13  number of reviews               102416 non-null  float64
 14  last review                     86706 non-null   object
 15  reviews per month               86720 non-null   float64
 16  review rate number              102273 non-null  float64
 17  calculated host listings count  102280 non-null  float64
 18  availability 365                102151 non-null  float64
 19  house_rules                     50468 non-null   object
dtypes: float64(7), int64(1), object(12)
memory usage: 15.7+ MB

In [13]:
df[['house_rules']].to_excel('outputText.xlsx')

In [52]:
df.drop(columns = 'host id', inplace = True)

In [50]:
df.head()

,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0

In [17]:
df.drop(columns = 'host id', inplace = True)

In [53]:
for i in df.columns:
    a = df[i].nunique()
    print ('value for', i, ' is ', a)

value for NAME  is  61281
value for host_identity_verified  is  2
value for host name  is  13190
value for neighbourhood group  is  7
value for neighbourhood  is  224
value for instant_bookable  is  2
value for cancellation_policy  is  3
value for room type  is  4
value for Construction year  is  20
value for price  is  1151
value for service fee  is  231
value for minimum nights  is  153
value for number of reviews  is  476
value for last review  is  2477
value for reviews per month  is  1016
value for review rate number  is  5
value for calculated host listings count  is  78
value for availability 365  is  438

In [55]:
df['minimum nights']= df['minimum nights'].fillna(0).astype(int)

In [58]:
df['service fee'] = df['service fee'].astype(str).str.replace('$', '', regex=False)
df['service fee'] = pd.to_numeric(df['service fee'], errors='coerce').fillna(0).astype(int)

In [60]:
df['service fee'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 102599 entries, 0 to 102598
Series name: service fee
Non-Null Count   Dtype
--------------   -----
102599 non-null  int64
dtypes: int64(1)
memory usage: 801.7 KB

In [62]:
df['minimum nights'] = df['minimum nights'].astype(int)

In [64]:
df.head()

,NAME,host_identity_verified,host name,neighbourhood group,neighbourhood,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365
0,Clean & quiet apt home by the park,unconfirmed,Madaline,Brooklyn,Kensington,False,strict,Private room,2020.0,$966,193,10,9.0,10/19/2021,0.21,4.0,6.0,286.0
1,Skylit Midtown Castle,verified,Jenna,Manhattan,Midtown,False,moderate,Entire home/apt,2007.0,$142,28,30,45.0,5/21/2022,0.38,4.0,2.0,228.0
2,THE VILLAGE OF HARLEM....NEW YORK !,NaN,Elise,Manhattan,Harlem,True,flexible,Private room,2005.0,$620,124,3,0.0,NaN,NaN,5.0,1.0,352.0
3,NaN,unconfirmed,Garry,Brooklyn,Clinton Hill,True,moderate,Entire home/apt,2005.0,$368,74,30,270.0,7/5/2019,4.64,4.0,1.0,322.0
4,Entire Apt: Spacious Studio/Loft by central park,verified,Lyndon,Manhattan,East Harlem,False,moderate,Entire home/apt,2009.0,$204,41,10,9.0,11/19/2018,0.10,3.0,1.0,289.0

In [87]:
cv = ['calculated host listings count']
for i in df.columns:
    if i in cv:
        df[i] = df[i].fillna(0)
        df[i] = df[i].astype(int)
    else:
        continue

df.head()

,NAME,host_identity_verified,host name,neighbourhood group,neighbourhood,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365
0,Clean & quiet apt home by the park,unconfirmed,Madaline,Brooklyn,Kensington,False,strict,Private room,2020,$966,193,10,9,10/19/2021,0.21,4,6,286
1,Skylit Midtown Castle,verified,Jenna,Manhattan,Midtown,False,moderate,Entire home/apt,2007,$142,28,30,45,5/21/2022,0.38,4,2,228
2,THE VILLAGE OF HARLEM....NEW YORK !,NaN,Elise,Manhattan,Harlem,True,flexible,Private room,2005,$620,124,3,0,NaN,NaN,5,1,352
3,NaN,unconfirmed,Garry,Brooklyn,Clinton Hill,True,moderate,Entire home/apt,2005,$368,74,30,270,7/5/2019,4.64,4,1,322
4,Entire Apt: Spacious Studio/Loft by central park,verified,Lyndon,Manhattan,East Harlem,False,moderate,Entire home/apt,2009,$204,41,10,9,11/19/2018,0.10,3,1,289

In [88]:
df.tail(20)

,NAME,host_identity_verified,host name,neighbourhood group,neighbourhood,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365
102579,Alexander's 2BR Luxury Quarters,verified,Juan,Brooklyn,Bedford-Stuyvesant,True,strict,Entire home/apt,2009,$294,59,3,123,6/26/2019,2.53,4,1,203
102580,"Near LGA, Citifield, US Open Tennis",verified,Carmen,Queens,East Elmhurst,False,strict,Private room,2013,$609,122,1,209,6/11/2019,4.38,3,1,270
102581,Bright Bedroom in Bustling Bed Stuy Brooklyn,unconfirmed,Amber,Brooklyn,Bedford-Stuyvesant,False,flexible,Private room,2022,$77,15,2,34,7/1/2019,0.70,5,3,299
102582,Private room in the best part of BK,verified,Brad,Brooklyn,Crown Heights,False,flexible,Private room,2011,$516,103,7,49,6/1/2019,1.01,2,1,425
102583,1 BR apartment sublet.,verified,Tassili,Manhattan,Harlem,True,flexible,Entire home/apt,2011,$247,49,5,0,NaN,NaN,2,1,327
102584,2 block walk from the beach in NYC,verified,Vladimir,Queens,Arverne,False,strict,Entire home/apt,2010,$566,113,2,89,5/26/2019,1.82,2,1,394
102585,Williamsburg family home -3 bedroom,verified,Lou,Brooklyn,Williamsburg,False,strict,Entire home/apt,2011,$643,129,5,4,3/27/2016,0.08,5,1,157
102586,Patio Oasis in Upper East Side,verified,Margaret,Manhattan,Upper East Side,True,strict,Entire home/apt,2003,$208,42,4,8,8/8/2016,0.17,5,1,159
102587,Adorable One-Bed in Williamsburg!,verified,Taylor,Brooklyn,Williamsburg,False,strict,Entire home/apt,2005,$388,78,1,66,6/16/2019,1.35,2,1,352
102588,"Loft Space for Events, Meetings & Shoots",unconfirmed,Kalin,Manhattan,Flatiron District,True,flexible,Entire home/apt,2016,$618,124,1,177,6/29/2019,3.78,4,1,410
102589,Lrg room 1 block from Prospect Park,unconfirmed,Dave,Brooklyn,Flatbush,False,flexible,Private room,2006,$306,61,3,0,NaN,NaN,1,1,200
102590,Wonderful artists' loft in Brooklyn,unconfirmed,Daniel,Brooklyn,Crown Heights,True,moderate,Entire home/apt,2003,$250,50,1,0,NaN,NaN,1,1,276
102591,Columbus Ave Apt 1 block from Park,verified,Lawrence,Manhattan,Upper West Side,False,strict,Entire home/apt,2005,"$1,139",228,5,17,1/4/2019,0.35,5,1,134
102592,3BR/1 Ba in TriBeCa w/ outdoor deck,unconfirmed,Nick,Manhattan,Tribeca,False,moderate,Entire home/apt,2016,$787,157,1,0,NaN,NaN,2,1,177
102593,"Welcoming, Clean, Cheap on St Marks",verified,Felipe,Manhattan,East Village,True,strict,Private room,2017,"$1,099",220,1,8,9/6/2015,0.16,4,2,152
102594,Spare room in Williamsburg,verified,Krik,Brooklyn,Williamsburg,False,flexible,Private room,2003,$844,169,1,0,NaN,NaN,3,1,227
102595,Best Location near Columbia U,unconfirmed,Mifan,Manhattan,Morningside Heights,True,moderate,Private room,2016,$837,167,1,1,7/6/2015,0.02,2,2,395
102596,"Comfy, bright room in Brooklyn",unconfirmed,Megan,Brooklyn,Park Slope,True,moderate,Private room,2009,$988,198,3,0,NaN,NaN,5,1,342
102597,Big Studio-One Stop from Midtown,unconfirmed,Christopher,Queens,Long Island City,True,strict,Entire home/apt,2015,$546,109,2,5,10/11/2015,0.10,3,1,386
102598,585 sf Luxury Studio,unconfirmed,Rebecca,Manhattan,Upper West Side,False,flexible,Entire home/apt,2010,"$1,032",206,1,0,NaN,NaN,3,1,69

In [93]:
bl = ['cancellation_policy', 'room type']

for i in df.columns:
    if i in bl :
        print (i,' value ',df[i].unique())
    else:
        continue

cancellation_policy  value  ['strict' 'moderate' 'flexible' nan]
room type  value  ['Private room' 'Entire home/apt' 'Shared room' 'Hotel room']